#!/bin/bash

source "./setup_config"

platform=$(uname | awk '{print tolower($0)}')
arch=$(uname -m)

[[ -f "setup_$platform" ]] && source "./setup_$platform"

tools=(
	flutter
	golang
)
for tool in "${tools[@]}"; do
	log "$tool setting up..."
	[[ -f "setup_$tool" ]] && source "./setup_$tool"
done
