#!/bin/bash

check_installed() {
	binary_name=$1
	package_name=$2

	if brew ls --versions $binary_name >/dev/null; then
		log "$binary_name installed, skipping..."
	else
		[ ! -f "$(which $binary_name)" ] &&
			log "$binary_name missing, installing..." &&
			brew install $package_name
	fi
}

check_installed zsh zsh
[[ ! $SHELL =~ "zsh" ]] && chsh -s "$(command -v zsh)"

check_installed jq jq
check_installed fzf fzf
check_installed fd fd
check_installed lazygit lazygit
check_installed eza eza
check_installed zoxide zoxide
check_installed nvim neovim
check_installed wget wget
check_installed git-delta git-delta
check_installed htop htop
check_installed mpv mpv
check_installed ripgrep ripgrep
check_installed yabai koekeishiya/formulae/yabai
check_installed skhd koekeishiya/formulae/skhd
check_installed tlrc tlrc
check_installed thefuck thefuck
check_installed tmux tmux

# Better osx than default
check_installed gawk gawk
check_installed coreutils coreutils

# Nerd Fonts
fonts_list=(
	font-meslo-lg-nerd-font
)
brew tap homebrew/cask-fonts
for font in "${fonts_list[@]}"; do
	brew install --cask "$font"
done

# Misc
check_installed scrcpy scrcpy

check_installed blueutil blueutil
relink $DOTFILE_PATH/darwin/sleep ~/.sleep
relink $DOTFILE_PATH/darwin/wakeup ~/.wakeup
sleep 1
echo $(blueutil --power) >~/.bluestatus
chmod +x ~/.bluestatus
if [[ $(networksetup -getairportpower en0) =~ "On" ]]; then
	echo 1 >~/.wifistatus
else
	echo 0 >~/.wifistatus
fi
chmod +x ~/.wifistatus

check_installed sleepwatcher sleepwatcher
sleep 1
brew services restart sleepwatcher
