#!/usr/bin/env lua

-- Add sketchybar module to package path
package.cpath = package.cpath .. ";/Users/" .. os.getenv("USER") .. "/.local/share/sketchybar_lua/?.so"

-- Initialize sbar module
sbar = require("sketchybar")

-- Load configuration
sbar.begin_config()
require("init")
sbar.hotload(true)
sbar.end_config()

sbar.event_loop()

-- Trigger update to run all scripts
sbar.update()
