#!/usr/bin/env zsh

# command cat ~/.nf

# Execute code in the background to not affect the current session
(
  # <https://github.com/zimfw/zimfw/blob/master/login_init.zsh>
  setopt LOCAL_OPTIONS EXTENDED_GLOB
  autoload -U zrecompile
  local zshconfig=~/.dotfiles/zsh

  # compile zcompdump, if modified, to increase startup speed.
  zcompdump="${zdotdir:-$home}/.zcompdump"
  if [[ -s "$zcompdump" && (! -s "${zcompdump}.zwc" || "$zcompdump" -nt "${zcompdump}.zwc") ]]; then
      zrecompile -pq "$zcompdump"
  fi
  # zcompile .zshrc
  zrecompile -pq ${zdotdir:-${home}}/.zshrc
  zrecompile -pq ${zdotdir:-${home}}/.zprofile
  zrecompile -pq ${zdotdir:-${home}}/.zshenv
  # recompile all zsh or sh
  for f in $zshconfig/**/*.*sh
  do
      zrecompile -pq $f
  done
) &!
